### ISSUE TITLE
Generated sourcemaps differ from LESSC and fail to resolve.

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#41]
Im struggling to get sourcemaps to resolve correctly. 

The following is a generated sourcemap from CLESC which chrome can not resolve:

`{"version" : 3,"sourceRoot": "/static/","file": "static/apps/_/less/ie-fixes.css","sources": ["static/apps/_/less/ie-fixes.less"],"names": [],"mappings": "0TAME,qCACE,iEACI,SAAU,CARlB,CAQoB,CARpB,CAQsB,EACd,KAAM,CATd,CASgB,CAThB,CASkB,EACV,aAAc,CAVtB,CAUwB,CAVxB,CAU0B,"}`

The below is a generated sourcemap from LESSC with the same invocation options which chrome can resolve:

`{"version":3,"sources":["/static/apps/_/less/ie-fixes.less"],"names":[],"mappings":"AAMsC,oCACA,iEAC9B,SAAA,EAAA,EAAA,EACA,KAAA,EAAA,EAAA,EACA,aAAA,EAAA,EAAA"}`

**Comment by TristanBrotherton** [comment]
I believe the issue may simply be just needing to add a preceding "/" to the sources URL. Is there a switch I could use to add this?

**Comment by BramvdKroef** [comment]
Try using `--source-map-rootpath=/ ` 
I've made an update that prefixes the rootpath to the sources.

**Comment by TristanBrotherton** [comment]
I've done some more testing here, your switch fixed the issue of not having the preceding slash in the file URL - however Chrome was still unable to resolve the sourcemap.
There are a few differences in the generated sourcemaps than that that LESSC generates, however I have not get be able to identify the breaking change. I'm trying to figure this out now.

**Comment by TristanBrotherton** [comment]
I did some testing here by compiling two sourcemaps, one with LESSC and one with CLESSC. I removed some whitespace in the CLESSC sourcemap, around the version and sources section to match LESSC. This had no effect.
I did notice the mappings themselves were different in the mapping section. When I changed the mapping dictionary to match, the sourcemap resolved.
I think therefore there is an issue with the generated mappings.

**Comment by TristanBrotherton** [comment]
After the latest few commits fixed some path issues I'm still having unable to resolve the sourcemaps in chrome:

The only discernible difference between the LESSC and CLESSC sourcemaps were some minor white-space and different values for the sources (which could be expected as CLESSC keeps comments in output that may affect line-nums).

I ran a test where I replaced the CLESSC sourcemap file with values for sources from LESSC and the sourcemap resolved, so my hypothesis is that somewhere CLESSC is generating invalid values here. 

CLESSC - CSS:
```
/* --------------------------------------------------------------
***************************************************************
Conditional Fixes for everyones favourite web browser.
***************************************************************
-------------------------------------------------------------- */@media screen and (min-width: 992px){html.ie body .row.flex-box-grid .flex-box-grid .flex-full-height{-ms-flex:1 0 0;flex:1 0 0;-webkit-flex:1 0 0}}
/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map */
```

CLESSC - map:

`{"version" : 3,"file": "ie-fixes.css","sources": ["/static/apps/_/less/ie-fixes.less"],"names": [],"mappings": ";;;;0TAME,+VACE,gaACI,yaAAU,+aACV,obAAM,0bACN,ucAAc,"}`

LESSC - CSS:
```
@media screen and (min-width:992px){html.ie body .row.flex-box-grid .flex-box-grid .flex-full-height{-ms-flex:1 0 0;flex:1 0 0;-webkit-flex:1 0 0}
}/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map */
```
LESSC - map:
{"version":3,"sources":["/static/apps/_/less/ie-fixes.less"],"names":[],"mappings":"AAMsC,oCACA,iEAC9B,SAAA,EAAA,EAAA,EACA,KAAA,EAAA,EAAA,EACA,aAAA,EAAA,EAAA"}

**Comment by TristanBrotherton** [comment]
I've been using this tool to parse the output, which appears materially different.

http://www.murzwin.com/base64vlq.html

**Comment by BramvdKroef** [comment]
The column counter got thrown off by the multi-line comment. It should work now.

**Comment by TristanBrotherton** [comment]
I built the latest ('fac2d04') I'm still unable to get the sourcemaps to resolve when using CLESSC. Let me know if there's more info I can provide. Here's my output from CLESSC / LESSC (which works).

CLESSC - CSS:
```
/* --------------------------------------------------------------
***************************************************************
Conditional Fixes for everyones favourite web browser.
***************************************************************
-------------------------------------------------------------- */
@media screen and (min-width: 992px){html.ie body .row.flex-box-grid .flex-box-grid .flex-full-height{-ms-flex:1 0 0;flex:1 0 0;-webkit-flex:1 0 0}}
/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map */
```
CLESSC - map

`{"version" : 3,"file": "ie-fixes.css","sources": ["/static/apps/_/less/ie-fixes.less"],"names": [],"mappings": ";;;;;AAME,qCACE,sGACI,+GAAU,qHACV,0HAAM,gIACN,6IAAc,"}`

LESSC - CSS
```
@media screen and (min-width:992px){html.ie body .row.flex-box-grid .flex-box-grid .flex-full-height{-ms-flex:1 0 0;flex:1 0 0;-webkit-flex:1 0 0}
}/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map */
```

LESSC - map
`{"version":3,"sources":["/static/apps/_/less/ie-fixes.less"],"names":[],"mappings":"AAMsC,oCACA,iEAC9B,SAAA,EAAA,EAAA,EACA,KAAA,EAAA,EAAA,EACA,aAAA,EAAA,EAAA"}`

**Comment by TristanBrotherton** [comment]
I did some further experimentation, and found that removing the trailing "," after the last mapping (which I noted LESSC did not add, helped (some but not all) sources remove:

**Comment by TristanBrotherton** [comment]
If there's any further details or test I can make to help with this, please let me know! This is the final piece of the puzzle before I can use CLESSC in our dev environment.

**Comment by BramvdKroef** [comment]
Try it again with the latest changes. I've made a few updates and it is working for me in firefox and chrome.

**Comment by TristanBrotherton** [comment]
Thank you this is now fixed!

This may not be the appropriate place to comment - but this now means I can use CLESSC in our dev eng. Would you consider making this a 1.0 release? If helpful I could provide binaries for Ubuntu and OSX
