### ISSUE TITLE
sourceMappingURL missing path, and sourcemap discrepancies. 

### ISSUE THREAD

**Issue by TristanBrotherton** [BramvdKroef/clessc#47]
The latest changes to sourcemaps have changed the sourcemapping URL in the compiled CSS.

CLESSC Compile Options:
```
        var lessc = spawn(options.clesscBin, [
            '--output='+ outpath,
            '--rootpath=/static/',
            '--source-map=' + outpath + '.map',
            '--source-map-basepath=/home/ubuntu/myvr/static/',
            '--source-map-rootpath=/static/',
            // '--no-color',
            '--include-path=static',
            inpath,
            outpath
        ]);
```

LESSC Compile Options:
```
        var lessc = spawn(options.lesscBin, [
            '--rootpath=/static/',
            '--source-map',
            '--source-map-basepath=/home/ubuntu/myvr/static/',
            '--source-map-rootpath=/static/',
            '--source-map-url=/' + outpath + '.map',
            '--no-color',
            '--include-path=static',
            inpath,
            outpath
        ]);
```

CLESSC Output (Note SourceMappingURL):
```
/* --------------------------------------------------------------
***************************************************************
Conditional Fixes for everyones favourite web browser.
***************************************************************
-------------------------------------------------------------- */@media screen and (min-width: 992px){html.ie body .row.flex-box-grid .flex-box-grid .flex-full-height{-ms-flex:1 0 0;flex:1 0 0;-webkit-flex:1 0 0}}
/*# sourceMappingURL=ie-fixes.css.map */

```

LESSC Output:
```
/* --------------------------------------------------------------
***************************************************************
Conditional Fixes for everyones favourite web browser.
***************************************************************
-------------------------------------------------------------- */
@media screen and (min-width: 992px) {
  html.ie body .row.flex-box-grid .flex-box-grid .flex-full-height {
    -ms-flex: 1 0 0;
    flex: 1 0 0;
    -webkit-flex: 1 0 0;
  }
}
/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map */
```

CLESSC Sourcemap (Note CSS URL and incorrect sources URL:
`{"version" : 3,"file": "ie-fixes.css","sources": ["/static/ie-fixes.less"],"names": [],"mappings": "0TAME,+VACE,gaACI,yaAAU,+aACV,obAAM,0bACN,ucAAc,"}`

LESSC Sourcemap:
`{"version":3,"sources":["/static/apps/_/less/ie-fixes.less"],"names":[],"mappings":";;;;;AAME,mBAAoC;EAQtC,IATI,GAAI,KAEJ,KAAI,cAAe,eAAe;IAC9B,eAAA;IACA,WAAA;IACA,mBAAA","file":"ie-fixes.css"}`

**Comment by BramvdKroef** [comment]
I see what you mean. I've made an update that fixes the sources and added the --source-map-url option.

**Comment by TristanBrotherton** [comment]
Thanks!

I now note that it will leave a / at the end of the url:

`'--source-map-url=/' + outpath + '.map',`

Returns in the CSS:

`/*# sourceMappingURL=/static/apps/_/less/ie-fixes.css.map/ */`

**Comment by TristanBrotherton** [comment]
Thanks, URL seems good but the "sources" in the generated sourcemap is now blank, using the same switches as above, this is the output of the map file:

CLESSC:
`{"version" : 3,"file": "ie-fixes.css","sources": [],"names": [],"mappings": "0TAME,+VACE,gaACI,yaAAU,+aACV,obAAM,0bACN,ucAAc,"}`

LESSC:

> {"version":3,"sources":["/static/apps/_/less/ie-fixes.less"],"names":[],"mappings":"AAMsC,oCACA,iEAC9B,SAAA,EAAA,EAAA,EACA,KAAA,EAAA,EAAA,EACA,aAAA,EAAA,EAAA"}

**Comment by BramvdKroef** [comment]
I fixed the bug.

**Comment by TristanBrotherton** [comment]
I see the correct path, however I am still unable to get sourcemaps to work. I will close this issue and post further details in that issue.
